import assert from 'node:assert/strict';
import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  symlinkSync,
  writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, test } from 'node:test';

import {
  APPS,
  PackageError,
  checkDependencyVersions,
  compareDistToSrc,
  descriptorFor,
  expectedJs,
  findSymlinks,
  findUnresolvedRequires,
  isShippedDistFile,
  listInstalled,
  packageFunction,
  parseYarnLock,
  workspaceDependencies,
  workspaceDir,
} from '../package-function.mjs';

const REPO = join(dirname(fileURLToPath(import.meta.url)), '../..');

function tree(root, files) {
  for (const [rel, content] of Object.entries(files)) {
    const abs = join(root, rel);
    mkdirSync(dirname(abs), { recursive: true });
    writeFileSync(abs, content);
  }
  return root;
}

const tmp = () => mkdtempSync(join(tmpdir(), 'pkgfn-'));

/**
 * A fake repo root with a Phase-0 looking document-ingestion and shared build
 * and an OLD zip at the deploy path. Nothing here reaches the yarn install:
 * every case fails in the pre-install checks.
 */
function fakeRepo(extra = {}) {
  return tree(tmp(), {
    'artifacts/document-ingestion.zip': 'the July build',
    'packages/document-ingestion/host.json': '{}',
    'packages/document-ingestion/package.json': '{"name":"@bcr/document-ingestion"}',
    'packages/document-ingestion/src/index.ts': "import './functions/health';",
    'packages/document-ingestion/src/functions/health.ts': '',
    'packages/document-ingestion/src/functions/health.test.ts': '',
    'packages/document-ingestion/src/services/batchIngestor.ts': '',
    'packages/document-ingestion/dist/index.js': 'require("./functions/health");',
    'packages/document-ingestion/dist/functions/health.js': "'identity-only'",
    'packages/document-ingestion/dist/services/batchIngestor.js': "'document.quarantined'",
    'packages/shared/package.json': '{"name":"@bcr/shared"}',
    'packages/shared/src/config.ts': '',
    'packages/shared/src/index.ts': '',
    'packages/shared/dist/config.js': 'botGateMode forbiddenTargetSitePaths',
    'packages/shared/dist/index.js': '',
    ...extra,
  });
}

describe('dist ↔ src', () => {
  test('expectedJs: one .js per non-test, non-declaration .ts', () => {
    const src = tree(tmp(), {
      'index.ts': '',
      'a/b.ts': '',
      'a/b.test.ts': '',
      'types.d.ts': '',
    });
    assert.deepEqual(expectedJs(src), ['a/b.js', 'index.js']);
  });

  test('an orphan (output of a deleted source) and a missing output are both reported', () => {
    const root = tree(tmp(), {
      'src/index.ts': '',
      'src/functions/health.ts': '',
      'src/functions/ingestDocument.ts': '',
      'dist/index.js': '',
      'dist/functions/health.js': '',
      'dist/functions/userTarget.js': '',
      'dist/functions/userTarget.js.map': '',
      'dist/functions/userTarget.d.ts': '',
      'dist/.tsbuildinfo': '',
    });
    const { orphans, missing, unshipped } = compareDistToSrc(join(root, 'dist'), join(root, 'src'));
    assert.deepEqual(orphans, ['functions/userTarget.js']);
    assert.deepEqual(missing, ['functions/ingestDocument.js']);
    assert.deepEqual(unshipped, []);
  });

  test('a non-TypeScript file in src is reported as unshipped', () => {
    const root = tree(tmp(), { 'src/index.ts': '', 'src/data.json': '{}', 'dist/index.js': '' });
    assert.deepEqual(compareDistToSrc(join(root, 'dist'), join(root, 'src')).unshipped, [
      'data.json',
    ]);
  });

  test('only compiled JavaScript is shipped from dist', () => {
    assert.equal(isShippedDistFile('/x/dist/index.js'), true);
    for (const f of ['index.js.map', 'index.d.ts', 'index.d.ts.map', '.tsbuildinfo', 'a.json']) {
      assert.equal(isShippedDistFile(`/x/dist/${f}`), false, f);
    }
  });

  test("every Phase-0 marker names a file that this repo's src still has", () => {
    // A rename that drops a marker file would make every package run fail at
    // deploy time; catch it here instead.
    for (const [name, { distMarkers }] of Object.entries(APPS)) {
      for (const [file] of distMarkers) {
        const src = join(REPO, 'packages', name, 'src', file.replace(/\.js$/, '.ts'));
        assert.equal(existsSync(src), true, `${name}: ${src}`);
      }
    }
  });
});

describe('yarn.lock', () => {
  const LOCK = `# This file is generated by running "yarn install" inside your project.

__metadata:
  version: 8
  cacheKey: 10c0

"@azure/abort-controller@npm:^2.0.0, @azure/abort-controller@npm:^2.1.2":
  version: 2.1.2
  resolution: "@azure/abort-controller@npm:2.1.2"
  languageName: node
  linkType: hard

"@bcr/shared@workspace:*, @bcr/shared@workspace:packages/shared":
  version: 0.0.0-use.local
  resolution: "@bcr/shared@workspace:packages/shared"
  languageName: unknown
  linkType: soft

"jose@npm:^5.8.0":
  version: 5.10.0
  resolution: "jose@npm:5.10.0"
  checksum: 10c0/abc
  languageName: node
  linkType: hard

"resolve@patch:resolve@npm%3A^1.20.0#optional!builtin<compat/resolve>":
  version: 1.22.12
  resolution: "resolve@patch:resolve@npm%3A1.22.12#optional!builtin<compat/resolve>::version=1.22.12&hash=c3c19d"
  languageName: node
  linkType: hard
`;

  test('maps every descriptor of a block to its locked version', () => {
    const { versions } = parseYarnLock(LOCK);
    assert.equal(versions.get('@azure/abort-controller@npm:^2.0.0'), '2.1.2');
    assert.equal(versions.get('@azure/abort-controller@npm:^2.1.2'), '2.1.2');
    assert.equal(versions.get(descriptorFor('jose', '^5.8.0')), '5.10.0');
  });

  test('resolutions: registry and patched packages, never the workspaces', () => {
    const { resolved } = parseYarnLock(LOCK);
    assert.deepEqual(
      [...resolved].sort(),
      ['@azure/abort-controller@2.1.2', 'jose@5.10.0', 'resolve@1.22.12'].sort(),
    );
  });

  test('descriptorFor keeps an explicit protocol', () => {
    assert.equal(descriptorFor('zod', '^3.23.8'), 'zod@npm:^3.23.8');
    assert.equal(descriptorFor('@bcr/shared', 'workspace:*'), '@bcr/shared@workspace:*');
  });

  test("parses this repo's yarn.lock: jose and zod are locked", () => {
    const { versions } = parseYarnLock(readFileSync(join(REPO, 'yarn.lock'), 'utf8'));
    const ingestion = JSON.parse(
      readFileSync(join(REPO, 'packages/document-ingestion/package.json'), 'utf8'),
    );
    for (const dep of ['jose', 'zod', '@anthropic-ai/sdk']) {
      assert.match(versions.get(descriptorFor(dep, ingestion.dependencies[dep])) ?? '', /^\d+\./);
    }
  });
});

describe('dependency versions', () => {
  test('ok only when yarn.lock, the tested tree and the package agree', () => {
    const rows = checkDependencyVersions([
      { dep: 'jose', lock: '5.10.0', tested: '5.10.0', zipped: '5.10.0' },
      { dep: 'zod', lock: '3.25.76', tested: '3.25.76', zipped: '3.25.80' },
      { dep: 'pino', lock: undefined, tested: '9.14.0', zipped: '9.14.0' },
    ]);
    assert.deepEqual(
      rows.map((r) => [r.dep, r.ok]),
      [
        ['jose', true],
        ['pino', false],
        ['zod', false],
      ],
    );
  });

  test('the same dependency declared by the app and shared at one version is one row', () => {
    const rows = checkDependencyVersions([
      { dep: 'zod', lock: '3.25.76', tested: '3.25.76', zipped: '3.25.76' },
      { dep: 'zod', lock: '3.25.76', tested: '3.25.76', zipped: '3.25.76' },
    ]);
    assert.equal(rows.length, 1);
    assert.equal(rows[0].ok, true);
  });

  test('a dependency locked at two versions fails: the package has room for one', () => {
    const rows = checkDependencyVersions([
      { dep: 'zod', lock: '3.25.76', tested: '3.25.76', zipped: '3.25.76' },
      { dep: 'zod', lock: '3.22.0', tested: '3.25.76', zipped: '3.25.76' },
    ]);
    assert.deepEqual(
      rows.map((r) => r.ok),
      [false, false],
    );
  });
});

describe('installed tree', () => {
  test('listInstalled walks scoped and nested packages and flags a symlink', () => {
    const root = tree(tmp(), {
      'node_modules/a/package.json': '{"name":"a","version":"1.0.0"}',
      'node_modules/a/node_modules/b/package.json': '{"name":"b","version":"2.0.0"}',
      'node_modules/@s/c/package.json': '{"name":"@s/c","version":"3.0.0"}',
      'node_modules/.yarn-state.yml': '',
      'node_modules/d/index.js': '',
    });
    symlinkSync(join(root, 'node_modules/a'), join(root, 'node_modules/e'));
    const got = listInstalled(join(root, 'node_modules')).map((p) =>
      p.problem ? `${p.path.split('/').pop()}: ${p.problem}` : `${p.name}@${p.version}`,
    );
    assert.deepEqual(got.sort(), [
      '@s/c@3.0.0',
      'a@1.0.0',
      'b@2.0.0',
      'd: no package.json name/version',
      'e: symlink',
    ]);
    assert.equal(findSymlinks(join(root, 'node_modules')).length, 1);
  });

  test('a require that only resolves in the monorepo around the package is reported', () => {
    // outer/node_modules/leak stands for the repo root's node_modules: node
    // resolution from the staging directory would find it, the archive would not.
    const outer = tree(tmp(), {
      'node_modules/leak/package.json': '{"name":"leak","version":"1.0.0","main":"i.js"}',
      'node_modules/leak/i.js': '',
      'pkg/node_modules/ok/package.json': '{"name":"ok","version":"1.0.0","main":"i.js"}',
      'pkg/node_modules/ok/i.js': '',
      'pkg/dist/index.js': [
        'require("ok");',
        'require("leak");',
        'require("absent");',
        'require("./here");',
        'require("./gone");',
        'require("node:fs");',
        'require("path");',
      ].join('\n'),
      'pkg/dist/here.js': '',
    });
    const got = findUnresolvedRequires(join(outer, 'pkg'), ['dist/index.js']).map(
      (u) => `${u.spec}: ${u.problem.split(':')[0]}`,
    );
    assert.deepEqual(got, [
      'leak: resolves outside',
      'absent: does not resolve',
      './gone: does not resolve',
    ]);
  });
});

describe('packageFunction', () => {
  const quiet = () => {};

  test('an unknown app name is refused', () => {
    assert.throws(
      () => packageFunction({ root: fakeRepo(), name: 'bogus', log: quiet }),
      PackageError,
    );
  });

  test('an orphan in dist fails the run and removes the old zip from the deploy path', () => {
    const root = fakeRepo({
      'packages/document-ingestion/dist/functions/userTarget.js': 'route: "user-target"',
    });
    const zip = join(root, 'artifacts/document-ingestion.zip');
    assert.equal(existsSync(zip), true);
    assert.throws(
      () => packageFunction({ root, name: 'document-ingestion', log: quiet }),
      (err) => err instanceof PackageError && /dist\/functions\/userTarget\.js/.test(err.message),
    );
    assert.equal(existsSync(zip), false, 'the July zip must not survive a failed run');
  });

  test('an orphan in @bcr/shared dist fails too', () => {
    const root = fakeRepo({ 'packages/shared/dist/fallback.js': '' });
    assert.throws(
      () => packageFunction({ root, name: 'document-ingestion', log: quiet }),
      (err) =>
        err instanceof PackageError && /@bcr\/shared.*\n.*dist\/fallback\.js/.test(err.message),
    );
  });

  test('a pre-Phase-0 @bcr/shared fails and removes the old zip', () => {
    const root = fakeRepo({ 'packages/shared/dist/config.js': 'fallbackSiteHostname' });
    assert.throws(
      () => packageFunction({ root, name: 'document-ingestion', log: quiet }),
      (err) => err instanceof PackageError && /not the Phase-0 build/.test(err.message),
    );
    assert.equal(existsSync(join(root, 'artifacts/document-ingestion.zip')), false);
  });

  test('an orphan in the dist of another workspace package the app ships fails too', () => {
    const root = fakeRepo({
      'packages/document-ingestion/package.json': JSON.stringify({
        name: '@bcr/document-ingestion',
        dependencies: { '@bcr/ledger-db': 'workspace:*', '@bcr/shared': 'workspace:*' },
      }),
      'packages/ledger-db/package.json': '{"name":"@bcr/ledger-db"}',
      'packages/ledger-db/src/index.ts': '',
      'packages/ledger-db/dist/index.js': '',
      'packages/ledger-db/dist/deleted.js': '',
    });
    assert.throws(
      () => packageFunction({ root, name: 'document-ingestion', log: quiet }),
      (err) =>
        err instanceof PackageError && /@bcr\/ledger-db.*\n.*dist\/deleted\.js/.test(err.message),
    );
    assert.equal(existsSync(join(root, 'artifacts/document-ingestion.zip')), false);
  });

  test('a missing build fails and removes the old zip', () => {
    const root = fakeRepo({ 'packages/document-ingestion/src/functions/ingestDocument.ts': '' });
    assert.throws(
      () => packageFunction({ root, name: 'document-ingestion', log: quiet }),
      (err) => err instanceof PackageError && /ingestDocument\.ts/.test(err.message),
    );
    assert.equal(existsSync(join(root, 'artifacts/document-ingestion.zip')), false);
  });
});

describe('workspace packages', () => {
  test('always @bcr/shared, plus the workspace dependencies, transitively, once each', () => {
    const manifests = {
      '@bcr/ledger-db': { dependencies: { '@bcr/shared': 'workspace:*', pg: '^8' } },
      '@bcr/shared': { dependencies: { zod: '^3' } },
    };
    assert.deepEqual(
      workspaceDependencies(
        { dependencies: { '@bcr/ledger-db': 'workspace:*', jose: '^5' } },
        (dep) => manifests[dep] ?? {},
      ),
      ['@bcr/ledger-db', '@bcr/shared'],
    );
    assert.deepEqual(workspaceDependencies({}), ['@bcr/shared']);
    // A registry package that happens to be scoped @bcr is not a workspace.
    assert.deepEqual(workspaceDependencies({ dependencies: { '@bcr/other': '^1.0.0' } }), [
      '@bcr/shared',
    ]);
    assert.equal(workspaceDir('@bcr/ledger-db'), 'ledger-db');
  });

  test('this repo: ingestion ships @bcr/ledger-db and @bcr/shared, the bot only @bcr/shared', () => {
    const read = (dir) =>
      JSON.parse(readFileSync(join(REPO, 'packages', dir, 'package.json'), 'utf8'));
    const byName = (dep) => read(workspaceDir(dep));
    assert.deepEqual(workspaceDependencies(read('document-ingestion'), byName), [
      '@bcr/ledger-db',
      '@bcr/shared',
    ]);
    assert.deepEqual(workspaceDependencies(read('teams-bot'), byName), ['@bcr/shared']);
  });
});
